name: merge_feature_to_develop
on:
  pull_request_review:
    types: [submitted]
    branches: ['feature/**']
jobs:
  pruebas: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: Configuración de entorno de python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Instalación de librerias y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Correr pruebas
        id: correr-pruebas
        run: |
          cd flaskr
          python -m unittest discover -s tests -v 
  automerge:
    needs: pruebas 
    name: Automerge
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@4536e8847eb62fe2f0ee52c8fa92d17aa97f932f"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_LABELS: ""
  buildbackdevelop:  
    needs: automerge
    name: Deploy back develop
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "af5479a1-52cc-4607-b4b8-162857a3b650"
          heroku_app_name: "devionicservice"
          heroku_email: "crisalmo138@gmail.com"         
        env:
          HD_FLASK_APP: "flaskr/app.py"      
  buildfrontdevelop: 
    needs: buildbackdevelop 
    name: Deploy front develop
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: "af5479a1-52cc-4607-b4b8-162857a3b650"
          heroku_app_name: "devionicfront" 
          heroku_email: "crisalmo138@gmail.com"
          appdir: "front-end/tutorial-canciones"  
        env:
         HD_ENVIRONMENT: "development"
